### ISSUE TITLE
Comma 2.1.1 not working with Rails 2.3.15?

### ISSUE THREAD

**Issue by stigmh** [comma-csv/comma#49]
Hi, I just updated an older app from Rails 2.3.14 to 2.3.15 and I'm now getting a "NoMethodError (undefined method 'status=' for ...): .../comma/render_as_csv.rb:41: in 'render_stream' /.../comma/render_as:csv.rb:25: in render" error, when I try to access the csv version of a controller. The app runs as normal except for that.

I am running comma 2.1.1, fastercsv 1.5.5, Rails 2.3.15 and Ruby 1.8.7.

I've spent a significant amount of time researching (including Google-ing) the issue without any luck. I have tried to use "require 'comma'" and to add ":status => 200" as a render option.

Thank you for your time.
